; Password Recovery - Successfully walked partner through recovering password.
::#pass::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down}{tab 6} Username and Password do not match{tab}User is getting 'Username and Password do not match' when trying to log in.{tab}Send Issue/Update: {Enter}User is getting 'Username and Password do not match' when trying to log in. {Enter}{Enter}Steps Taken: {Enter}Advised partner to {Enter}- Use the 'Forgot Username or Password' button.{Enter}- Enter email and send instructions.{Enter}- Use the reset link to reset your password.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner was able to reset their password and log in.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passAR::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 2}{tab 2}{down 3}{tab}{enter}{tab 3}Username and Password do not match{tab}User is getting 'Username and Password do not match' when trying to log in.{tab}Send Issue/Update: {Enter}User is getting 'Username and Password do not match' when trying to log in. {Enter}{Enter}Steps Taken: {Enter}Advised partner to {Enter}- Use the 'Forgot Username or Password' button.{Enter}- Enter email and send instructions.{Enter}- Use the reset link to reset your password.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner was able to reset their password and log in.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passNE::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 3}{tab 2}{down 3}{tab}{enter}{tab 3}Username and Password do not match{tab}User is getting 'Username and Password do not match' when trying to log in.{tab}Send Issue/Update: {Enter}User is getting 'Username and Password do not match' when trying to log in. {Enter}{Enter}Steps Taken: {Enter}Advised partner to {Enter}- Use the 'Forgot Username or Password' button.{Enter}- Enter email and send instructions.{Enter}- Use the reset link to reset your password.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner was able to reset their password and log in.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passNV::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 4}{tab 2}{down 3}{tab}{enter}{tab 3}Username and Password do not match{tab}User is getting 'Username and Password do not match' when trying to log in.{tab}Send Issue/Update: {Enter}User is getting 'Username and Password do not match' when trying to log in. {Enter}{Enter}Steps Taken: {Enter}Advised partner to {Enter}- Use the 'Forgot Username or Password' button.{Enter}- Enter email and send instructions.{Enter}- Use the reset link to reset your password.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner was able to reset their password and log in.{Enter}{Enter}Additional Notes: {Enter}{End}

; Password Recovery - Partner has no profile in NWEA.
::#passnopro::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down}{tab 6} User Needs Login{tab}User is trying to log in but isn't able to.{tab}Send Issue/Update: {Enter}User is trying to log in but isn't able to. {Enter}{Enter}Steps Taken: {Enter}Verified partner doesn't have a profile in MAP. {Enter}Advised partner to get in touch with their System Administrator and have them create a profile.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passnoproAR::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 2}{tab 2}{down 4}{tab}{enter}{tab 3}User Needs Login{tab}User is trying to log in but isn't able to.{tab}Send Issue/Update: {Enter}User is trying to log in but isn't able to. {Enter}{Enter}Steps Taken: {Enter}Verified partner doesn't have a profile in MAP. {Enter}Advised partner to get in touch with their System Administrator and have them create a profile.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passnoproNE::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 3}{tab 2}{down 4}{tab}{enter}{tab 3}User Needs Login{tab}User is trying to log in but isn't able to.{tab}Send Issue/Update: {Enter}User is trying to log in but isn't able to. {Enter}{Enter}Steps Taken: {Enter}Verified partner doesn't have a profile in MAP. {Enter}Advised partner to get in touch with their System Administrator and have them create a profile.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passnoproNV::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 4}{tab 2}{down 4}{tab}{enter}{tab 3}User Needs Login{tab}User is trying to log in but isn't able to.{tab}Send Issue/Update: {Enter}User is trying to log in but isn't able to. {Enter}{Enter}Steps Taken: {Enter}Verified partner doesn't have a profile in MAP. {Enter}Advised partner to get in touch with their System Administrator and have them create a profile.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}

; Password Recovery - Partner's email is incorrect.
::#passemail::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down}{tab 6} Unable to Reset Password{tab}User isn't able to reset their password.{tab}Send Issue/Update: {Enter}User isn't able to reset their password. {Enter}{Enter}Steps Taken: {Enter}Verified user's email in the system is different from their actual email. {Enter}Advised partner to get in touch with their System Administrator and correct the email in MAP.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passemailAR::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 2}{tab 2}{down 4}{tab}{enter}{tab 3}Unable to Reset Password{tab}User isn't able to reset their password.{tab}Send Issue/Update: {Enter}User isn't able to reset their password. {Enter}{Enter}Steps Taken: {Enter}Verified user's email in the system is different from their actual email. {Enter}Advised partner to get in touch with their System Administrator and correct the email in MAP.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passemailNE::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 3}{tab 2}{down 4}{tab}{enter}{tab 3}Unable to Reset Password{tab}User isn't able to reset their password.{tab}Send Issue/Update: {Enter}User isn't able to reset their password. {Enter}{Enter}Steps Taken: {Enter}Verified user's email in the system is different from their actual email. {Enter}Advised partner to get in touch with their System Administrator and correct the email in MAP.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}
::#passemailNV::{shift down}{tab 10}{shift up}{down}{tab}{down 7}{tab 2}{down}{tab}{down 4}{tab 2}{down 4}{tab 2}{down 4}{tab}{enter}{tab 3}Unable to Reset Password{tab}User isn't able to reset their password.{tab}Send Issue/Update: {Enter}User isn't able to reset their password. {Enter}{Enter}Steps Taken: {Enter}Verified user's email in the system is different from their actual email. {Enter}Advised partner to get in touch with their System Administrator and correct the email in MAP.{Enter}{Enter}Define Resolution/Next Steps: {Enter}Partner will contact their System Administrator.{Enter}{Enter}Additional Notes: {Enter}{End}

; Student name is missing from test drop down list - Status Confirmed
::#testmissingconfirmed::{shift down}{tab 10}{shift up}{down}{tab}{down 5}{tab 2}{down}{tab}{down 7}{tab 2}{down}{tab 6}Student Missing in Test Drop Down List{tab}Partner can't find student's name when trying to log into test.{tab}Issue/Update: {Enter}Student was kicked out of test and could not find their name. {Enter}{Enter}Steps Taken: {Enter}Advised Partner to {Enter}- Select student in proctor's test session. {Enter}- Select Action > Do Not Confirm. {Enter}- Refresh student browser. {Enter}{Enter}Define Resolution/Next Steps: {Enter}Student can now find their name.{Enter}{Enter}Additional Notes: {Enter}{End}
